### ISSUE TITLE
Broken due to missing Starcounter.QueryProcessor 1.0.0-beta-14606

### ISSUE THREAD

**Issue by linkdata** [Starcounter/Starcounter.Core.Samples#1]
```
/starcounter.core.samples/Starcounter.Core.Samples.csproj : warning NU1603: Starcounter.Core.Level1QPBridge 0.6.0 depends on Starcounter.QueryProcessor (>= 1.0.0-beta-14606) but Starcounter.QueryProcessor 1.0.0-beta-14606 was not found. An approximate best match of Starcounter.QueryProcessor 1.0.0-beta-14838 was resolved.
  Generating MSBuild file /starcounter.core.samples/obj/Starcounter.Core.Samples.csproj.nuget.g.props.
  Generating MSBuild file /starcounter.core.samples/obj/Starcounter.Core.Samples.csproj.nuget.g.targets.
  Restore completed in 25.42 sec for /starcounter.core.samples/Starcounter.Core.Samples.csproj.
/starcounter.core.samples/Starcounter.Core.Samples.csproj : warning NU1603: Starcounter.Core.Level1QPBridge 0.6.0 depends on Starcounter.QueryProcessor (>= 1.0.0-beta-14606) but Starcounter.QueryProcessor 1.0.0-beta-14606 was not found. An approximate best match of Starcounter.QueryProcessor 1.0.0-beta-14838 was resolved.
/starcounter.core.samples/Starcounter.Core.Samples.csproj : warning NU1603: Starcounter.Core.Level1QPBridge 0.6.0 depends on Starcounter.QueryProcessor (>= 1.0.0-beta-14606) but Starcounter.QueryProcessor 1.0.0-beta-14606 was not found. An approximate best match of Starcounter.QueryProcessor 1.0.0-beta-14838 was resolved.
/usr/share/dotnet/sdk/2.0.0/Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [/starcounter.core.samples/Starcounter.Core.Samples.csproj]
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Starcounter.ErrorCodes, Version=0.12.767.0, Culture=neutral, PublicKeyToken=d2df1e81d0ca3abf'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Starcounter.SqlProcessor.SqlProcessor.<>c.<LoadGlobalSetspecIndexHandle>b__57_0()
   at Starcounter.Core.Database.Context.Run(Transaction txn, Action action)
   at Starcounter.Core.Database.Context.Transact(Action action, TransactOptions options)
   at Starcounter.Core.Level1QPBridge.Dependencies.TransactIgnoreHooks(Action a)
   at Starcounter.Core.Level1QPBridge.Initializer.Start()
   at Starcounter.Core.Hosting.Connection.Start()
   at Starcounter.Core.Hosting.DefaultAppHost.Start()
   at Program.Main(String[] args) in /starcounter.core.samples/Program.cs:line 78
```
cc @bigwad

**Comment by bigwad** [comment]
I see it raises a warning on Starcounter.QueryProcessor and fails due to Starcounter.ErrorCodes. Nevertheless, don't know why Starcounter.QueryProcessor 1.0.0-beta-14606 has disappeared. I can republish it, but something is wrong here. Do we have a retention policy of any kind? Another solution would be to set version ranges in .nuspec.

**Comment by linkdata** [comment]
> Do we have a retention policy of any kind?

https://docs.myget.org/docs/reference/package-retention

**Comment by linkdata** [comment]
Our settings are currently to keep *all* released packages, and the *2* latest pre-release versions.
We had to scale that down from the default as we ran out of space on MyGet.

**Comment by linkdata** [comment]
To solve this particular issue, re-uploading the package in question and pinning it (to prevent removal of a certain pre-release version) will be enough.
