### ISSUE TITLE
Upgrade to a new version of Nova

### ISSUE THREAD

**Issue by ErlendLandro** [Starcounter/Starcounter.Core.Samples#5]
It uses 0.7.0. It should use the latest version

**Comment by ErlendLandro** [comment]
This is blocked since the Bluestar package doesn't work properly with Nova 0.8.7. When a new Bluestar is released, we can upgrade the version

**Comment by ErlendLandro** [comment]
> This is blocked since the Bluestar package doesn't work properly with Nova 0.8.7. When a new Bluestar is released, we can upgrade the version

This is incorrect. The problem is that it isn't possible to switch between latest level0 binaries and the latest Bluestar package. @alemoi is working on fixing this

**Comment by ErlendLandro** [comment]
The build fails with this:

```
/root/.nuget/packages/runtime.ubuntu.16.04-x64.runtime.native.starcounter.bluestar/2.4.0-pre-012531/runtimes/ubuntu.16.04-x64/native/scdblog: error while loading shared libraries: libaio.so.1: cannot open shared object file: No such file or directory
Unhandled Exception: Starcounter.Nova.StarcounterException: ScErrDataManagerDisconnected (SCERR4296): Communication with data manager failed because client was disconnected by data manager.
   at Starcounter.Nova.Hosting.Connection.ConnectToDataManager(StarcounterOptions options)
   at Starcounter.Nova.Hosting.Connection.Start()
   at Starcounter.Nova.Hosting.DefaultAppHost.Start()
   at Program.Main(String[] args) in /starcounter.core.samples/Program.cs:line 78
```

I'm able to run this without a problem on Ubuntu locally. Investigating

**Comment by ErlendLandro** [comment]
libaio doesn't seem to be installed. Trying to include it.

**Comment by ErlendLandro** [comment]
New try with `libaio`:

```

/root/.nuget/packages/runtime.ubuntu.16.04-x64.runtime.native.starcounter.bluestar/2.4.0-pre-012531/runtimes/ubuntu.16.04-x64/native/scdblog: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /root/.nuget/packages/runtime.ubuntu.16.04-x64.runtime.native.starcounter.bluestar/2.4.0-pre-012531/runtimes/ubuntu.16.04-x64/native/scdblog)
Unhandled Exception: Starcounter.Nova.StarcounterException: ScErrDataManagerDisconnected (SCERR4296): Communication with data manager failed because client was disconnected by data manager.
   at Starcounter.Nova.Hosting.Connection.ConnectToDataManager(StarcounterOptions options)
   at Starcounter.Nova.Hosting.Connection.Start()
   at Starcounter.Nova.Hosting.DefaultAppHost.Start()
   at Program.Main(String[] args) in /starcounter.core.samples/Program.cs:line 78
```
